-- Luxtory BD cloud database (Supabase)
-- Run this once in Supabase SQL Editor.
create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  category text not null default 'অন্যান্য',
  description text,
  content text not null,
  source_url text,
  status text not null default 'published' check (status in ('draft','published')),
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  category text not null default 'অন্যান্য',
  content text not null,
  source_url text,
  rights_accepted boolean not null default false,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.admins enable row level security;
alter table public.books enable row level security;
alter table public.submissions enable row level security;

create or replace function public.is_luxtory_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admins a
    where a.user_id = auth.uid()
  );
$$;

revoke all on function public.is_luxtory_admin() from public;
grant execute on function public.is_luxtory_admin() to anon, authenticated;

grant select on public.books to anon, authenticated;
grant insert, update, delete on public.books to authenticated;
grant insert on public.submissions to anon, authenticated;
grant select, update on public.submissions to authenticated;

create policy "public can read published books"
on public.books for select
to anon, authenticated
using (status = 'published' or public.is_luxtory_admin());

create policy "admins can add books"
on public.books for insert
to authenticated
with check (public.is_luxtory_admin());

create policy "admins can update books"
on public.books for update
to authenticated
using (public.is_luxtory_admin())
with check (public.is_luxtory_admin());

create policy "admins can delete books"
on public.books for delete
to authenticated
using (public.is_luxtory_admin());

create policy "anyone can submit a story"
on public.submissions for insert
to anon, authenticated
with check (rights_accepted = true and status = 'pending');

create policy "admins can review submissions"
on public.submissions for select
to authenticated
using (public.is_luxtory_admin());

create policy "admins can update submissions"
on public.submissions for update
to authenticated
using (public.is_luxtory_admin())
with check (public.is_luxtory_admin());

-- After creating your admin user in Authentication > Users,
-- run this with that user's UUID:
-- insert into public.admins(user_id) values ('YOUR-ADMIN-USER-UUID');

-- Expose these tables through Supabase Data API if your project requires explicit exposure.
